version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - BZN=${BZN:-DE-LU}
      - TIMEZONE=${TIMEZONE:-Europe/Amsterdam}
      - PRICES_API_BASE=${PRICES_API_BASE:-https://api.energy-charts.info}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/prices || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8080/api
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    driver: bridge